Break adding tweets without the right environment
Instantiating the tweepy object when the environment is missing
gives a confusing error:

    tweepy.error.TweepError: Failed to send request: Only unicode
    objects are escapable. Got None of type <class 'NoneType'>.

I wasted time trying to figure out what was wrong with my code
rather than my environment, so use `os.environ` so it blows up
if the environment is not properly set up.